### ISSUE TITLE
Bug: Catch Multiple Error and Warnings for shiny

### ISSUE THREAD

**Issue by jan-abel-inwt** [Pandora-IsoMemo/shiny-tools#20]
Currently, within the context of error handling, when multiple errors or warnings occur, they replace each other, resulting in only one being displayed. This behavior limits our ability to diagnose and address multiple issues simultaneously. To enhance our error handling mechanism, we need to adjust the `tryCatchWithWarningsAndErrors function` so that it retains and presents all encountered errors and warnings, providing a comprehensive overview of potential issues. This modification will enable more effective troubleshooting.

**Comment by arunge** [comment]
The feature was integrated into our `tryCatch` function and will be available in the apps with future feature updates of the apps.
I am closing here.
